---
- name: Update and reboot
  hosts: all
  gather_facts: no
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: Reboot servers
      reboot:
        pre_reboot_delay: 0
        msg: "reboot in 90 seconds"
